/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.oe.ziel.domain;

import org.testng.annotations.*;
import static org.testng.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        System.out.println("test");
    }
}
